### ISSUE TITLE
There is no accept on HttpRequest

### ISSUE THREAD

**Issue by Tiliavir** [cyclosproject/ng-openapi-gen#23] opened 2019-07-02 05:50 UTC
Hi,

I'm trying to use this tool, but get errors during build:

```
[ERROR] ERROR in src/app/generated/api/request-builder.ts(176,82): error TS2345: Argument of type '{ accept?: string; responseType?: "text" | "blob" | "arraybuffer" | "json"; reportProgress?: bool...' is not assignable to parameter of type '{ headers?: HttpHeaders; reportProgress?: boolean; params?: HttpParams; responseType?: "text" | "...'.
[ERROR]   Object literal may only specify known properties, and 'accept' does not exist in type '{ headers?: HttpHeaders; reportProgress?: boolean; params?: HttpParams; responseType?: "text" | "...'.
[ERROR] 
```

For some reason "accept" is not a valid property of HttpRequest options param in ng6 - 8, but it is used in your "request-builder.ts".

**Comment by luisfpg** [comment] 2019-07-15 10:47
Sorry, but can't reproduce this.
Can you send a more complete error trace, and exactly which angular version are you using?

**Comment by luisfpg** [comment] 2019-07-15 11:15
I think I got how could it break, although I can't reproduce it.
Maybe you use some other TypeScript compiler flag... But should be fixed.

**Closed** 2019-07-15 11:15 UTC
