### ISSUE TITLE
Not adding reference of Models used

### ISSUE THREAD

**Issue by SharmaHarsh7** [cyclosproject/ng-openapi-gen#37] opened 2019-08-09 04:55 UTC
I generated the TS code from my server OpenAPI.

Where I have 2 models
```
/* tslint:disable */
import { Test } from './test';
export interface User  {
  EmpCode: string;
  EmpId: number;
  Login?: null | Login;
  Name: string;
  test?: Test;
}
```
and 

```
/* tslint:disable */
export interface Login  {
  Password?: null | string;
  UserName?: null | string;
}

```

As you can see it is not adding reference of **Login** into **User**, only an enum type **Test** is added.

**Comment by luisfpg** [comment] 2019-08-09 11:22
I think this is a duplicate of #31 
Can you, please, also test the `one-of-path` branch?
Follow the instructions of https://github.com/cyclosproject/ng-openapi-gen#developing-and-contributing for the build.

**Comment by SharmaHarsh7** [comment] 2019-08-09 14:34
Sure.. will share the results with you

**Comment by luisfpg** [comment] 2019-08-14 16:31
I'm closing this as I'm pretty sure it was a duplicate.
If the problem persists, we reopen it.

**Closed by luisfpg** 2019-08-14 16:31 UTC
