### ISSUE TITLE
Wrong responseType if response in schema has multiple params

### ISSUE THREAD

**Issue by fnnzzz** [cyclosproject/ng-openapi-gen#157] opened 2021-04-20 11:55 UTC
Faced a problem that the wrong type is generated for the request builder (`text` instead `json`), when schema has multiple params separated with `; `. 

I found the reason, the method `inferResponseType` checks for the end of the line, what falls under our case.
https://github.com/cyclosproject/ng-openapi-gen/blob/c42cc33e8a316bfcefe4d20a02102dc65f2d08ed/lib/operation-variant.ts#L51-L59

<img width="463" alt="image" src="https://user-images.githubusercontent.com/3502507/115391029-a56f8a80-a1e7-11eb-998d-e3de7cf5c2b4.png">

As a temporary solution I use `customizedResponseType`, but there is a problem with the fact that you need to support all new pathes.

Thank you.

**Comment by luisfpg** [comment] 2021-06-14 11:21
This is a duplicate of #154. Will be released soon.

**Closed by luisfpg** 2021-06-14 11:21 UTC
Labels: duplicate
